@host=https://localhost:7234
Get {{host}}/dinners 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZTkwY2NmYy0xNDFlLTRiODYtYjQwMC0yMzQ5N2UwM2M2MWQiLCJnaXZlbl9uYW1lIjoiNDUiLCJmYW1pbHlfbmFtZSI6IlFBWiIsImp0aSI6ImNlMzQ1MjJkLTY3NTQtNGM5Yy1iY2UyLTc4MmRiNWU3ZWQ4ZCIsImV4cCI6MTY4ODg5MjQ2NywiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.b36z7MsrQtFqxqpONXBkV_rxUBAUpy6j4KJFfrpUQTQ
